version: "2"
services:
  webserver:
    image: nginx:alpine
    restart: always
    ports: 
      - "8080:80"
    volumes:
      - ./public:/html
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
